/**
 * useKgoose - React hook for invoking MCP tools via kgoose
 * DO NOT MODIFY - Auto-generated by Block App Kit
 *
 * Use this hook in React components to call external services.
 * All authentication is handled automatically by kgoose.
 */

import { useState, useCallback } from 'react'
import { kgoose } from '../lib/kgoose'

interface UseKgooseOptions {
  onSuccess?: (result: unknown) => void
  onError?: (error: Error) => void
}

interface UseKgooseResult<T> {
  invoke: (toolName: string, params: Record<string, unknown>) => Promise<T>
  isLoading: boolean
  error: Error | null
  data: T | null
  reset: () => void
}

/**
 * Generic hook for invoking any MCP tool.
 *
 * @example
 * function MyComponent() {
 *   const { invoke, isLoading, error, data } = useKgoose()
 *
 *   const handleClick = async () => {
 *     await invoke('datadog/list-monitors', { appId: 'my-app' })
 *   }
 *
 *   return <button onClick={handleClick} disabled={isLoading}>Fetch</button>
 * }
 */
export function useKgoose<T = unknown>(options?: UseKgooseOptions): UseKgooseResult<T> {
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<Error | null>(null)
  const [data, setData] = useState<T | null>(null)

  const invoke = useCallback(async (
    toolName: string,
    params: Record<string, unknown>
  ): Promise<T> => {
    setIsLoading(true)
    setError(null)

    try {
      const result = await kgoose.invoke<T>(toolName, params)
      setData(result)
      options?.onSuccess?.(result)
      return result
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err))
      setError(error)
      options?.onError?.(error)
      throw error
    } finally {
      setIsLoading(false)
    }
  }, [options])

  const reset = useCallback(() => {
    setIsLoading(false)
    setError(null)
    setData(null)
  }, [])

  return { invoke, isLoading, error, data, reset }
}

/**
 * Hook for Slack operations.
 *
 * @example
 * const { sendMessage, isLoading } = useSlack()
 * await sendMessage('#general', 'Hello!')
 */
export function useSlack() {
  const { invoke, ...rest } = useKgoose()
  return {
    ...rest,
    sendMessage: (channel: string, text: string) =>
      invoke('slack/send_message', { channel, text }),
    postToThread: (channel: string, threadTs: string, text: string) =>
      invoke('slack/post_to_thread', { channel, thread_ts: threadTs, text }),
  }
}

/**
 * Hook for Linear operations.
 *
 * @example
 * const { createIssue } = useLinear()
 * await createIssue({ title: 'Bug', teamId: 'TEAM-1' })
 */
export function useLinear() {
  const { invoke, ...rest } = useKgoose()
  return {
    ...rest,
    createIssue: (params: { title: string; teamId: string; description?: string }) =>
      invoke('linear/create_issue', params),
    updateIssue: (issueId: string, updates: Record<string, unknown>) =>
      invoke('linear/update_issue', { issueId, ...updates }),
  }
}

/**
 * Hook for Airtable operations.
 *
 * @example
 * const { query, createRecord } = useAirtable()
 * const records = await query('baseId', 'tableId')
 */
export function useAirtable() {
  const { invoke, ...rest } = useKgoose()
  return {
    ...rest,
    query: (baseId: string, tableId: string, filterQuery?: string) =>
      invoke('airtable/query', { baseId, tableId, query: filterQuery }),
    createRecord: (baseId: string, tableId: string, fields: Record<string, unknown>) =>
      invoke('airtable/create_record', { baseId, tableId, fields }),
  }
}

/**
 * Generic hook for any provider.
 *
 * @example
 * const datadog = useProvider('datadog')
 * await datadog.call('list-monitors', { appId: 'my-app' })
 */
export function useProvider(provider: string) {
  const { invoke, ...rest } = useKgoose()
  return {
    ...rest,
    call: (action: string, params: Record<string, unknown>) =>
      invoke(`${provider}/${action}`, params),
  }
}

export default useKgoose
