/**
 * kgoose Client - Unified interface for MCP tool invocation
 * DO NOT MODIFY - Auto-generated by Block App Kit
 *
 * All external API calls go through kgoose. You don't need to manage
 * API credentials - kgoose handles authentication automatically.
 *
 * Action types follow the convention: {provider}/{action}
 * Examples: slack/send_message, linear/create_issue, datadog/list-monitors
 */

// Configuration
const APP_ID = 'dashboard-refresher'

// Types
export interface KgooseActionRequest {
  type: 'cloudflare-action'
  actionId: string
  action: {
    type: string
    payload: {
      title?: string
      description?: string
      [key: string]: unknown
    }
  }
}

export interface KgooseActionResponse {
  type: 'cloudflare-action-response'
  actionId: string
  success: boolean
  error?: string
  result?: unknown
}

// Pending action callbacks
const pendingActions = new Map<string, {
  resolve: (result: unknown) => void
  reject: (error: Error) => void
}>()

// Generate unique action ID
function generateActionId(): string {
  return `${APP_ID}-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`
}

// Listen for action responses from G2
if (typeof window !== 'undefined') {
  window.addEventListener('message', (event) => {
    if (event.data?.type === 'cloudflare-action-response') {
      const response = event.data as KgooseActionResponse
      const pending = pendingActions.get(response.actionId)

      if (pending) {
        pendingActions.delete(response.actionId)
        if (response.success) {
          pending.resolve(response.result)
        } else {
          pending.reject(new Error(response.error || 'Action failed'))
        }
      }
    }
  })
}

/**
 * Invoke an MCP tool through kgoose.
 *
 * @param toolName - Tool to invoke in {provider}/{action} format
 * @param params - Parameters for the tool
 * @param options - Optional metadata for G2 confirmation UI
 *
 * @example
 * await kgoose.invoke('slack/send_message', {
 *   channel: '#general',
 *   text: 'Hello!'
 * })
 */
export async function invoke<T = unknown>(
  toolName: string,
  params: Record<string, unknown>,
  options?: { title?: string; description?: string }
): Promise<T> {
  const actionId = generateActionId()

  return new Promise((resolve, reject) => {
    // Store callback
    pendingActions.set(actionId, {
      resolve: resolve as (result: unknown) => void,
      reject,
    })

    // Send to G2 parent
    const message: KgooseActionRequest = {
      type: 'cloudflare-action',
      actionId,
      action: {
        type: toolName,
        payload: {
          title: options?.title || toolName,
          description: options?.description,
          ...params,
        },
      },
    }

    window.parent.postMessage(message, '*')

    // Timeout after 60 seconds
    setTimeout(() => {
      if (pendingActions.has(actionId)) {
        pendingActions.delete(actionId)
        reject(new Error('Action timed out'))
      }
    }, 60000)
  })
}

export const kgoose = {
  invoke,
}

export default kgoose
