/**
 * kgoose Client - Unified interface for MCP tool invocation
 * DO NOT MODIFY - Auto-generated by Block App Kit
 *
 * This client handles all external API calls through kgoose.
 * Users don't need to manage API credentials - kgoose handles auth.
 *
 * Works in two modes:
 * 1. Embedded in g2: Uses postMessage to parent window
 * 2. Standalone: Direct API calls to kgoose endpoint
 */

import { logger } from './logger'

// Types for action requests/responses
export interface KgooseAction {
  type: string
  payload: Record<string, unknown>
}

export interface KgooseActionRequest {
  type: 'cloudflare-action'
  actionId: string
  action: {
    type: string
    payload: {
      title?: string
      description?: string
      [key: string]: unknown
    }
  }
}

export interface KgooseActionResponse {
  type: 'cloudflare-action-response'
  actionId: string
  success: boolean
  error?: string
  result?: unknown
}

// Configuration
const APP_ID = 'dashboard-refresher'
const KGOOSE_ENDPOINT = typeof window !== 'undefined'
  ? '/api/kgoose/v1/actions'  // Client-side: relative path (proxied)
  : 'https://kgoose.sqprod.co/v1/actions'  // Server-side: direct

// Pending action callbacks (for postMessage mode)
const pendingActions = new Map<string, {
  resolve: (result: unknown) => void
  reject: (error: Error) => void
}>()

// Check if running inside g2 iframe
function isEmbeddedInG2(): boolean {
  if (typeof window === 'undefined') return false
  try {
    return window.parent !== window && window.parent.location.hostname.includes('g2')
  } catch {
    // Cross-origin - likely embedded
    return window.parent !== window
  }
}

// Generate unique action ID
function generateActionId(): string {
  return `${APP_ID}-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`
}

// Listen for action responses (postMessage mode)
if (typeof window !== 'undefined') {
  window.addEventListener('message', (event) => {
    if (event.data?.type === 'cloudflare-action-response') {
      const response = event.data as KgooseActionResponse
      const pending = pendingActions.get(response.actionId)

      if (pending) {
        pendingActions.delete(response.actionId)
        if (response.success) {
          pending.resolve(response.result)
        } else {
          pending.reject(new Error(response.error || 'Action failed'))
        }
      }
    }
  })
}

/**
 * Invoke an MCP tool through kgoose.
 *
 * @param toolName - The tool to invoke (e.g., 'slack.send_message', 'linear.create_issue')
 * @param params - Parameters for the tool
 * @param options - Optional metadata for display in confirmation UI
 * @returns Promise resolving to the tool result
 *
 * @example
 * // Send a Slack message
 * const result = await kgoose.invoke('slack.send_message', {
 *   channel: '#general',
 *   text: 'Hello from Block App Kit!'
 * }, {
 *   title: 'Send Slack Message',
 *   description: 'Posting to #general channel'
 * })
 *
 * @example
 * // Create a Linear issue
 * const issue = await kgoose.invoke('linear.create_issue', {
 *   title: 'Bug: Login broken',
 *   teamId: 'TEAM-123'
 * })
 */
export async function invoke<T = unknown>(
  toolName: string,
  params: Record<string, unknown>,
  options?: { title?: string; description?: string }
): Promise<T> {
  const actionId = generateActionId()

  logger.info('kgoose.invoke', { toolName, actionId })

  if (isEmbeddedInG2()) {
    // PostMessage mode - let g2 handle it
    return invokeViaPostMessage<T>(actionId, toolName, params, options)
  } else {
    // Direct API mode
    return invokeViaAPI<T>(actionId, toolName, params)
  }
}

async function invokeViaPostMessage<T>(
  actionId: string,
  toolName: string,
  params: Record<string, unknown>,
  options?: { title?: string; description?: string }
): Promise<T> {
  return new Promise((resolve, reject) => {
    // Store callback
    pendingActions.set(actionId, {
      resolve: resolve as (result: unknown) => void,
      reject,
    })

    // Send to parent
    const message: KgooseActionRequest = {
      type: 'cloudflare-action',
      actionId,
      action: {
        type: toolName,
        payload: {
          title: options?.title || toolName,
          description: options?.description,
          ...params,
        },
      },
    }

    window.parent.postMessage(message, '*')

    // Timeout after 30 seconds
    setTimeout(() => {
      if (pendingActions.has(actionId)) {
        pendingActions.delete(actionId)
        reject(new Error('Action timed out'))
      }
    }, 30000)
  })
}

async function invokeViaAPI<T>(
  actionId: string,
  toolName: string,
  params: Record<string, unknown>
): Promise<T> {
  const response = await fetch(KGOOSE_ENDPOINT, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-App-ID': APP_ID,
      'X-Action-ID': actionId,
    },
    body: JSON.stringify({
      tool: toolName,
      params,
    }),
  })

  if (!response.ok) {
    const error = await response.text()
    logger.error('kgoose.invoke failed', { toolName, status: response.status, error })
    throw new Error(`kgoose error: ${error}`)
  }

  const result = await response.json()
  logger.info('kgoose.invoke success', { toolName, actionId })
  return result as T
}

/**
 * Convenience methods for common tools
 */
export const kgoose = {
  invoke,

  slack: {
    sendMessage: (channel: string, text: string) =>
      invoke('slack.send_message', { channel, text }, {
        title: 'Send Slack Message',
        description: `Posting to ${channel}`,
      }),

    postToThread: (channel: string, threadTs: string, text: string) =>
      invoke('slack.post_to_thread', { channel, thread_ts: threadTs, text }),
  },

  linear: {
    createIssue: (params: { title: string; teamId: string; description?: string }) =>
      invoke('linear.create_issue', params, {
        title: 'Create Linear Issue',
        description: params.title,
      }),

    updateIssue: (issueId: string, params: Record<string, unknown>) =>
      invoke('linear.update_issue', { issueId, ...params }),
  },

  airtable: {
    query: (baseId: string, tableId: string, query?: string) =>
      invoke('airtable.query', { baseId, tableId, query }),

    createRecord: (baseId: string, tableId: string, fields: Record<string, unknown>) =>
      invoke('airtable.create_record', { baseId, tableId, fields }),
  },

  calendar: {
    searchEvents: (query: string, calendarIds?: string[]) =>
      invoke('google_calendar.search_events', { query, calendarIds }),

    createEvent: (params: { summary: string; start: string; end: string; calendarId?: string }) =>
      invoke('google_calendar.create_event', params),
  },
}

export default kgoose
